name: BuddyChannels
main: BuddyChannels\Main
version: 1.0
api: 1.12.0
author: mwvent
website: http://wattz.org.uk/mcpe

commands:
 buddychannels:
   aliases: [chan, ch]
   description: BuddyChannels commands.
   permission: buddychannels.commands.buddychannels
 shout:
   aliases: [sh]
   description: BuddyChannels shout.
   permission: buddychannels.commands.shout
 block:
   aliases: [blk]
   description: BuddyChannels block user from (your) chat.
   permission: buddychannels.commands.block
 unblock:
   aliases: [unblk]
   description: BuddyChannels unblock user from (your) chat.
   permission: buddychannels.commands.unblock
 mute:
   aliases: []
   description: BuddyChannels mute the public channel (if you are in your own channel).
   permission: buddychannels.commands.mute
 unmute:
   aliases: []
   description: BuddyChannels unmute the public channel (if you are in your own channel).
   permission: buddychannels.commands.unmute
 me:
   aliases: [emote]
   description: BuddyChannels emote.
   permission: buddychannels.commands.me
permissions:
 buddychannels:
  default: true
  description: "Buddychannels permissions"
  children:
   buddychannels.commands:
    default: true
    description: "Buddychannels commands"
    children:
     buddychannels.commands.info:
      description: "Show info"
      default: true
     buddychannels.commands.list:
      description: "List channels"
      default: true
     buddychannels.commands.join:
      description: "Join a channel"
      default: true
     buddychannels.commands.buddychannels:
      description: "Main buddychannels command"
      default: true
     buddychannels.commands.shout:
      default: true
      description: "Buddychannels allow shouting"
     buddychannels.commands.block:
       description: "Buddychannels allow block another user"
       default: true
     buddychannels.commands.unblock:
       description: "Buddychannels allow unblock another user"
       default: true
     buddychannels.commands.me:
       description: "Buddychannels use me command to emote"
       default: true
     buddychannels.commands.mute:
       description: "Buddychannels allow mute public channel"
       default: true
     buddychannels.commands.unmute:
       description: "Buddychannels allow umute public channel"
       default: true