---
datetime-format: "H:i:s"
log-on-console: true
# this server id and name - useful if you need plugin to link the chat of server instances together
# server-id must be numeric, server-name can be text
server-id: 0
server-name: untitled
# load chat from other server ids (share chat between server instances)
connect-server-chat: false
# do not use localhost for server it doesnt work - use 127.0.0.1 instead
mysql-server: 127.0.0.1
mysql-user: username
mysql-pass: password
database: pocketmine
# player ranks datasource - currentley supported values are none and pureperms
read-ranks-from: none
# use a rank override db table 
use-rank-override: false
rank-override-table: custom-ranks
# tables created by buddypress - you may be using a prefix
buddypress-bp_groups_members-tablename: bp_groups_members
buddypress-bp_groups-tablename: bp_groups
# tables created by wordpress - you be using a prefix
wordpress-users-tablename: users
buddypress-activity-tablename: bp_activity
# tables that will be created and belong to buddychannels
buddychannels-users-table: buddychannels_users
buddychannels-servers-table: buddychannels_servers
buddychannels-chatlog-table: buddychannels_chatlog
buddychannels-user-meta-table: buddychannels_users_meta
# website to mention when telling players where to do groups
website: "HTTPS://YOURWEBSITE.WHATEVER"
# spam filter
use-spamfilter: false
spamfilter-time-interval: 60
spamfilter-max-duplicates-per-interval: 2
spamfilter-max-messages-per-interval: 6
# swearing is immature filter
# turns a user into baby where each word they type is converted into baby babble for
# a time period - the swear words are hard coded to have as few false positives as possible
swearing-is-immature: false
swearing-is-immature-punishment-period: 60
# dumb swear filter - censors patterns from the badwords.txt list
# no punishment due to high potential of false positives
use-wordlist-censor: false
# rss input
# for posting website updates as a message in the game
# uses website setting about for making chat messages
use-rss: false
rss-url: "https://YOUR.SITE/rssfeed"
# use website advertisements
use-website-advertisements: true
# don't send user a website advertisment if they have logged in the last x hours
leave-alone-period: 12
# how often to advertise in approximate seconds ( *20 ticks )
ad-freq: 120
# advertisement messages - use the <WEBSITE> tag to replace with the website setting above
ad-messages:
  - "&fYou havent visited the website for a while! Please visit &d<WEBSITE> &f for chat, post pictures and activate pets and custom ranks. Everything is &4FREE! Plus get rid of these annoying messages for a while &6;-)"
  - "&fWe miss you on &d<WEBSITE> &ffor our &4FREE &fsocial network, pets and custom ranks. Plus get rid of these annoying messages for a while &6;-P"
  - "&fPlease come (re)visit &d<WEBSITE>&f! &4FREE &4FREE &4FREE - &fsocial network, pets, custom ranks. And get rid of these annoying messages for a while &6;-D"
  - "&fDid we mention our awesome website?? - &d<WEBSITE>&f! Come login with your player name and password + removes these annoying messages for a while &6;-O"
  - "&fPlease come visit &d<WEBSITE>&f! This server is paid at no cost to you by website advertisements every page you view supports the server. Plus you rid of these annoying messages for a while &68-)"
...
